### ISSUE TITLE
Doesn't work if `DuplicateRecordFields` is turned on

### ISSUE THREAD

**Issue by gergoerdi** [fumieval/barbies-th#3]
Example source illustrating the problem:

```
{-# LANGUAGE TemplateHaskell, FlexibleInstances, DeriveGeneric #-}
{-# LANGUAGE DuplicateRecordFields #-}
import Barbies
import Data.Barbie.TH

declareBareB [d|
  data R = MkR
      { foo :: Int
      } |]
```

This fails with:

```
src/Foo.hs:6:1: error:
    Illegal variable name: ‘$sel:foo:MkR’
    When splicing a TH declaration:
      data R_0 sw_1 h_2
    = MkR_3 {$sel:foo:MkR_4 :: (Barbies.Internal.Wear.Wear sw_1
                                                           h_2
                                                           GHC.Types.Int)}
    deriving GHC.Generics.Generic
  |
6 | declareBareB [d|
  | ^^^^^^^^^^^^^^^^...
```

**Comment by gergoerdi** [comment]
This is caused by [GHC mangling record field names when `DuplicateRecordFields` is turned on](https://gitlab.haskell.org/ghc/ghc/-/wikis/records/overloaded-record-fields/duplicate-record-fields#mangling-selector-names).

**Comment by expipiplus1** [comment]
This doesn't seem to work for me (`barbies-th-0.1.7`).

```haskell
{-# language TemplateHaskell #-}
{-# language FlexibleInstances #-}
{-# language TypeFamilies #-}
{-# language DuplicateRecordFields #-}

import           Barbies.TH

declareBareB [d|
  data A = A
    { a :: Int
    }  |]
```

fails with 

```
❯ ghc A.hs
[1 of 1] Compiling A                ( A.hs, A.o, A.dyn_o )

A.hs:10:1: error:
    Illegal variable name: ‘$sel:a:A’
    When splicing a TH declaration:
      instance Barbies.TH.AccessorsB (A_0 Barbies.Internal.Wear.Covered)
    where Barbies.TH.baccessors = A_1 (Barbies.TH.LensB ($sel:a:A_2) (\x_3 b_4 -> b_4{$sel:a:A_2 = x_3}))
   |
10 | declareBareB [d|
   | ^^^^^^^^^^^^^^^^...
```

Has there been a regression since https://github.com/fumieval/barbies-th/pull/4 was merged?

**Comment by gergoerdi** [comment]
A quick bisection shows:

```
02ec21b9fa2fb1d09cec8efc8d1db2a5bd7a84ca is the first bad commit
commit 02ec21b9fa2fb1d09cec8efc8d1db2a5bd7a84ca
Author: Fumiaki Kinoshita <fumiexcel@gmail.com>
Date:   Wed Jun 3 13:34:56 2020 +0900

    generate lenses
```

**Comment by expipiplus1** [comment]
fixing it now

**Comment by Elvecent** [comment]
Not sure if related but I get "symbol already defined" errors in Assembler stage when having DuplicateRecordFields on and actual data definitions with duplicate record fields
